// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfM6qxnAa7f0C0KQ_PxgE2TZfga2aYZw',
    appId: '1:416901106003:web:386681780995c29f1779a6',
    messagingSenderId: '416901106003',
    projectId: 'toktok-92575',
    authDomain: 'toktok-92575.firebaseapp.com',
    storageBucket: 'toktok-92575.firebasestorage.app',
    measurementId: 'G-C7CGGHMCQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0bwP8er2wrXOG593AOUGdPD48xlwI-Y',
    appId: '1:416901106003:android:98a97e85737d7b3e1779a6',
    messagingSenderId: '416901106003',
    projectId: 'toktok-92575',
    storageBucket: 'toktok-92575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxxe3oSQ3q30xC4IroCfxUzLgg1ajJkg8',
    appId: '1:416901106003:ios:0a5f776e1cd12d2e1779a6',
    messagingSenderId: '416901106003',
    projectId: 'toktok-92575',
    storageBucket: 'toktok-92575.firebasestorage.app',
    iosBundleId: 'com.example.toktokapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxxe3oSQ3q30xC4IroCfxUzLgg1ajJkg8',
    appId: '1:416901106003:ios:0a5f776e1cd12d2e1779a6',
    messagingSenderId: '416901106003',
    projectId: 'toktok-92575',
    storageBucket: 'toktok-92575.firebasestorage.app',
    iosBundleId: 'com.example.toktokapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZfM6qxnAa7f0C0KQ_PxgE2TZfga2aYZw',
    appId: '1:416901106003:web:c00cb4e077e016b51779a6',
    messagingSenderId: '416901106003',
    projectId: 'toktok-92575',
    authDomain: 'toktok-92575.firebaseapp.com',
    storageBucket: 'toktok-92575.firebasestorage.app',
    measurementId: 'G-TY8FR1SPXM',
  );
}
